### PR TITLE
Vcost storyboard

### PR DESCRIPTION
**Pull request by ks578**

### CODE REVIEW

**Comment by ary1111** [comment]
@ks578 why were the following scripts deleted?

- ContinuousMovement.cs
- HandPresence.cs
- MancualXRControl.cs

**Comment by ks578** [comment]
> @ks578 why were the following scripts deleted?
> 
> * ContinuousMovement.cs
> * HandPresence.cs
> * MancualXRControl.cs


I had to create builds of the scenes but it didn't let me create builds with those scripts.

**Comment by ary1111** [comment]
@ks

> > @ks578 why were the following scripts deleted?
> > 
> > * ContinuousMovement.cs
> > * HandPresence.cs
> > * MancualXRControl.cs
> 
> @ary1111 I had to create builds of the scenes but it didn't let me create builds with those scripts.

@ks578 Can you try the following? Restore the files, disable "Initialize XR on Startup" in Project Settings --> XR Plug-in Management and then try to build a scene. Please let me know if you have any issues.

**Comment by ks578** [comment]
> @ks
> 
> > > @ks578 why were the following scripts deleted?
> > > 
> > > * ContinuousMovement.cs
> > > * HandPresence.cs
> > > * MancualXRControl.cs
> > 
> > 
> > @ary1111 I had to create builds of the scenes but it didn't let me create builds with those scripts.
> 
> @ks578 Can you try the following? Restore the files, disable "Initialize XR on Startup" in Project Settings --> XR Plug-in Management and then try to build a scene. Please let me know if you have any issues.

@ary1111 I already have it disabled. I re-tried just now and it still will not build with those scripts in the project file.

**Comment by ary1111** [comment]
> > @ks
> > > > @ks578 why were the following scripts deleted?
> > > > 
> > > > * ContinuousMovement.cs
> > > > * HandPresence.cs
> > > > * MancualXRControl.cs
> > > 
> > > 
> > > @ary1111 I had to create builds of the scenes but it didn't let me create builds with those scripts.
> > 
> > 
> > @ks578 Can you try the following? Restore the files, disable "Initialize XR on Startup" in Project Settings --> XR Plug-in Management and then try to build a scene. Please let me know if you have any issues.
> 
> @ary1111 I already have it disabled. I re-tried just now and it still will not build with those scripts in the project file.

@ks578 What platform are you building for?

**Comment by ks578** [comment]
> > > @ks
> > > > > @ks578 why were the following scripts deleted?
> > > > > 
> > > > > * ContinuousMovement.cs
> > > > > * HandPresence.cs
> > > > > * MancualXRControl.cs
> > > > 
> > > > 
> > > > @ary1111 I had to create builds of the scenes but it didn't let me create builds with those scripts.
> > > 
> > > 
> > > @ks578 Can you try the following? Restore the files, disable "Initialize XR on Startup" in Project Settings --> XR Plug-in Management and then try to build a scene. Please let me know if you have any issues.
> > 
> > 
> > @ary1111 I already have it disabled. I re-tried just now and it still will not build with those scripts in the project file.
> 
> @ks578 What platform are you building for?

@ary1111 Windows 64bit

**Comment by ary1111** [comment]
@ks578 What Unity version are you using?

**Comment by ks578** [comment]
@ary1111 I am using 2019.3.14

**Comment by ary1111** [comment]
@ks578 Okay, I'm not sure why you weren't able to build, but there were a few bug fixes in the release that should resolve the build issue. If you have build/play issues you should bring them up in the issue tracker or with Trudi or I. These kinds of issues should be brought up before deleting files that are part of the project, as all of those scripts will be used. Please restore the scripts you deleted in your branch, with the files in the latest VCOST branch. If you continue to have any issues, please let us know.

**Comment by trudiQ** [comment]
> @ks578 Okay, I'm not sure why you weren't able to build, but there were a few bug fixes in the release that should resolve the build issue. If you have build/play issues you should bring them up in the issue tracker or with Trudi or I. These kinds of issues should be brought up before deleting files that are part of the project, as all of those scripts will be used. Please restore the scripts you deleted in your branch, with the files in the latest VCOST branch. If you continue to have any issues, please let us know.

@ks578 Doga, could you restore all the files that were initially in the VCOST branch back to the storyboard branch and test on your own machine to see if you could build and run the storyboard project this time? Please get those files from the latest VCOST branch where the issues that may cause your compile errors should have been fixed. Please let us know if you still have the issue. Thanks!

**Pull request merged**
